site_name: JiGuang Docs
site_author: JiGuang Offical
site_url: https://docs.jiguang.cn/en/
repo_url: https://github.com/jpush/jpush-docs/
site_favicon: img/favicon.ico
site_description: JPush, JMessage, Android Push, iOS Push, APNs, Push Notification
copyright: Copyright 2011-2018, jiguang.cn, All Rights Reserved. <br />粤ICP备12056275号-13 深圳市和讯华谷信息技术有限公司
theme: 'mkdocs'
theme_dir: 'jiguang'
docs_dir: 'docs'
extra_css: []
extra_javascript: []
extra_templates: []

pages:

- home: 'index.md'

- JPush:

  - Getting Started Guide:
    - 'Product Introduction of JPush': 'jpush/guideline/intro.md'
    - 'Console Usage Guide': 'jpush/console/Instructions.md'
    - 'JPush SMS Supplement': 'jpush/guideline/push-SMS-intro.md'
    - 'Rich Push Development Guide': 'jpush/advanced/rich_push.md'
    - 'FAQ': 'jpush/guideline/faq.md'
  - Android:
    - 'Android SDK Overview': 'jpush/client/Android/android_sdk.md'
    - '3 Minutes Demo': 'jpush/client/Android/android_3m.md'
    - 'Android SDK Integration Guide': 'jpush/client/Android/android_guide.md'
    - 'Android SDK Debugging Guide': 'jpush/client/Android/android_debug_guide.md'
    - 'Android SDK Advanced Tutorial': 'jpush/client/Android/android_senior.md'
    - 'Android SDK API': 'jpush/client/Android/android_api.md'
    - 'Android SDK FAQ': 'jpush/client/Android/android_faq.md'
  - iOS:
    - 'iOS SDK Overview': 'jpush/client/iOS/ios_sdk.md'
    - 'iOS SDK Integration Guide': 'jpush/client/iOS/ios_guide_new.md'
    - 'iOS SDK Debugging Guide': 'jpush/client/iOS/ios_debug_guide.md'
    - 'iOS Certificate Setup Guide': 'jpush/client/iOS/ios_cer_guide.md'
    - 'New Features of iOS': 'jpush/client/iOS/ios_new_fetures.md'
    - 'iOS SDK API': 'jpush/client/iOS/ios_api.md'
    - 'iOS SDK FAQ': 'jpush/client/iOS/ios_faq.md'
  - WindowsPhone:
    - 'Overview of Windows Phone SDK': 'jpush/client/WindowsPhone/winphone_sdk.md'
    - '3 Minutes Fast Demo of Windows Phone': 'jpush/client/WindowsPhone/winphone_3m.md'
    - 'Integration Guide of Windows Phone SDK ': 'jpush/client/WindowsPhone/winphone_guide.md'
    - 'Windows Phone API': 'jpush/client/WindowsPhone/winphone_api.md'
  - REST API:
    - 'Overview of REST API': 'jpush/server/push/server_overview.md'
    - 'Push API v3': 'jpush/server/push/rest_api_v3_push.md'
    - 'Report API v3': 'jpush/server/push/rest_api_v3_report.md'
    - 'Device API v3': 'jpush/server/push/rest_api_v3_device.md'
    - 'Schedule API v3': 'jpush/server/push/rest_api_push_schedule.md'
    - 'Admin API v1': 'jpush/server/push/rest_api_admin_api_v1.md'
    - 'HTTP Status Code': 'jpush/server/push/http_status_code.md'
  - Advanced:
    - 'Application Scenarios of JPush': 'jpush/advanced/scenes.md'
    - 'Advanced Topics of JPush': 'jpush/advanced/topics.md'
  - Client Integration Plugin: 'jpush/client/client_plugins.md'
  - Server SDK:
    - 'Java SDK': 'jpush/server/sdk/java_sdk.md'
    - 'Python SDK': 'jpush/server/sdk/python_sdk.md'
    - 'PHP SDK': 'jpush/server/sdk/php_sdk.md'
    - 'Ruby SDK': 'jpush/server/sdk/ruby_sdk.md'
    - 'C# SDK': 'jpush/server/sdk/csharp_sdk.md'
    - 'Node.js SDK': 'jpush/server/sdk/nodejs_sdk.md'
  - Old Documents:
    - 'REST API v2 - Push': 'jpush/server/old/rest_api_v2_push.md'
    - 'REST API v2 - Report': 'jpush/server/old/rest_api_v2_report.md'
  - Recent Updates: 'jpush/updates.md'
  - Download: 'jpush/resources.md'

- JMessage:

  - Getting Started Guide:
    - 'Product Introduction of JMessage': 'jmessage/guideline/jmessage_guide.md'
    - 'FAQ': 'jmessage/guideline/faq.md'
  - Android:
    - 'SDK Development Guide': 'jmessage/client/im_sdk_android.md'
    - 'SDK Integration Guide': 'jmessage/client/jmessage_android_guide.md'
    - 'Definition of SDK ErrorCode': 'jmessage/client/im_errorcode_android.md'
    - 'SDK API Doc': 'jmessage/client/javadoc.md'
  - iOS:
    - 'SDK Development Guide': 'jmessage/client/im_sdk_ios.md'
    - 'SDK Integration Guide': 'jmessage/client/jmessage_ios_guide.md'
    - 'Definition of SDK ErrorCode': 'jmessage/client/im_errorcode_ios.md'
    - 'SDK API Doc': 'jmessage/client/iOSdoc.md'
  - Web:
    - 'SDK Development Guide V2': 'jmessage/client/im_sdk_js_v2.md'
    - 'SDK Development Guide': 'jmessage/client/im_sdk_js.md'
    - 'WeChat Applet SDK': 'jmessage/client/im_sdk_wxapplet.md'
    - 'Definition of SDK ErrorCode': 'jmessage/client/im_errorcode_js.md'
  - PC:
    - 'SDK Development Guide': 'jmessage/client/im_sdk_win.md'
    - 'SDK API Doc': 'jmessage/client/windoc.md'
  - REST API:
    - 'REST API': 'jmessage/server/rest_api_im.md'
    - 'REST Report V2': 'jmessage/server/rest_api_im_report_v2.md'
    - 'REST Report': 'jmessage/server/rest_api_im_report.md'
    - 'Definition of Server ErrorCode': 'jmessage/client/im_errorcode_server.md'
  - Advanced:
    - 'Message Agreement': 'jmessage/advanced/im_message_protocol.md'
    - 'Business Objects': 'jmessage/advanced/im_objects.md'
    - 'Real-time Message Routing': 'jmessage/advanced/jmessage_callback.md'
  - Client Integration Plugin: 'jmessage/client/client_plugins.md'
  - Server SDK:
    - 'Java SDK': 'jmessage/server/sdk/java_sdk.md'
    - 'Python SDK': 'jmessage/server/sdk/python_sdk.md'
    - 'PHP SDK': 'jmessage/server/sdk/php_sdk.md'
    - 'C# SDK': 'jmessage/server/sdk/csharp_sdk.md'
  - Recent Updates: 'jmessage/updates.md'
  - Download: 'jmessage/resources.md'
